scrapy crawl books1 -o books1.json
scrapy crawl books2 -o books2.json
scrapy crawl books3 -o books3.json
scrapy crawl books4 -o books4.json
scrapy crawl books5 -o books5.json
scrapy crawl books6 -o books6.json
scrapy crawl books7 -o books7.json
scrapy crawl books8 -o books8.json
scrapy crawl books9 -o books9.json