scrapy crawl cars1 -o cars1.json
scrapy crawl cars2 -o cars2.json
scrapy crawl cars3 -o cars3.json
scrapy crawl cars4 -o cars4.json
scrapy crawl cars5 -o cars5.json
scrapy crawl cars6 -o cars6.json
scrapy crawl cars7 -o cars7.json
scrapy crawl cars8 -o cars8.json
scrapy crawl cars9 -o cars9.json
scrapy crawl cars10 -o cars10.json
scrapy crawl cars11 -o cars11.json
scrapy crawl cars12 -o cars12.json
scrapy crawl cars13 -o cars13.json