scrapy crawl books1 -o books1.json
scrapy crawl books2 -o books2.json
scrapy crawl books3 -o books3.json
scrapy crawl books4 -o books4.json
scrapy crawl books5 -o books5.json
scrapy crawl books6 -o books6.json
scrapy crawl books7 -o books7.json
scrapy crawl books8 -o books8.json
scrapy crawl books9 -o books9.json
# scrapy crawl movies1 -o movies1.json
# scrapy crawl movies2 -o movies2.json
# scrapy crawl movies3 -o movies3.json
# scrapy crawl movies4 -o movies4.json
# scrapy crawl movies5 -o movies5.json
# scrapy crawl movies6 -o movies6.json
# scrapy crawl movies7 -o movies7.json
# scrapy crawl movies8 -o movies8.json
# scrapy crawl movies9 -o movies9.json
# scrapy crawl movies10 -o movies10.json
# scrapy crawl mobiles1 -o mobiles1.json
# scrapy crawl mobiles2 -o mobiles2.json
# scrapy crawl mobiles3 -o mobiles3.json
# scrapy crawl mobiles4 -o mobiles4.json
# scrapy crawl mobiles5 -o mobiles5.json
# scrapy crawl mobiles6 -o mobiles6.json
# scrapy crawl mobiles7 -o mobiles7.json
# scrapy crawl computers1 -o computers1.json
# scrapy crawl computers2 -o computers2.json
# scrapy crawl computers3 -o computers3.json
# scrapy crawl computers4 -o computers4.json
# scrapy crawl computers5 -o computers5.json
# scrapy crawl computers6 -o computers6.json
# scrapy crawl computers7 -o computers7.json
# scrapy crawl cameras1 -o cameras1.json
# scrapy crawl cameras2 -o cameras2.json
# scrapy crawl cameras3 -o cameras3.json
# scrapy crawl cameras4 -o cameras4.json
# scrapy crawl cameras5 -o cameras5.json
# scrapy crawl cameras6 -o cameras6.json
# scrapy crawl cameras7 -o cameras7.json
# scrapy crawl cameras8 -o cameras8.json
# scrapy crawl cameras9 -o cameras9.json
# scrapy crawl cameras10 -o cameras10.json
# scrapy crawl cameras11 -o cameras11.json
# scrapy crawl cameras12 -o cameras12.json
# scrapy crawl home1 -o home1.json
# scrapy crawl home2 -o home2.json
# scrapy crawl home3 -o home3.json
# scrapy crawl home4 -o home4.json
# scrapy crawl home5 -o home5.json
# scrapy crawl home6 -o home6.json
# scrapy crawl home7 -o home7.json
# scrapy crawl home8 -o home8.json
# scrapy crawl home9 -o home9.json
# scrapy crawl home10 -o home10.json
# scrapy crawl home11 -o home11.json
# scrapy crawl toys1 -o toys1.json
# scrapy crawl toys2 -o toys2.json
# scrapy crawl toys3 -o toys3.json
# scrapy crawl toys4 -o toys4.json
# scrapy crawl toys5 -o toys5.json
# scrapy crawl toys6 -o toys6.json
# scrapy crawl toys7 -o toys7.json
# scrapy crawl toys8 -o toys8.json
# scrapy crawl sports1 -o sports1.json
# scrapy crawl sports2 -o sports2.json
# scrapy crawl sports3 -o sports3.json
# scrapy crawl sports4 -o sports4.json
# scrapy crawl sports5 -o sports5.json
# scrapy crawl sports6 -o sports6.json
# scrapy crawl sports7 -o sports7.json
# scrapy crawl sports8 -o sports8.json
# scrapy crawl sports9 -o sports9.json
# scrapy crawl sports10 -o sports10.json
# scrapy crawl sports11 -o sports11.json
# scrapy crawl beauty1 -o beauty1.json
# scrapy crawl beauty2 -o beauty2.json
# scrapy crawl beauty3 -o beauty3.json
# scrapy crawl beauty4 -o beauty4.json
# scrapy crawl beauty5 -o beauty5.json
# scrapy crawl beauty6 -o beauty6.json
# scrapy crawl beauty7 -o beauty7.json
# scrapy crawl beauty8 -o beauty8.json
# scrapy crawl clothing1 -o clothing1.json
# scrapy crawl clothing2 -o clothing2.json
# scrapy crawl clothing3 -o clothing3.json
# scrapy crawl clothing4 -o clothing4.json
# scrapy crawl clothing5 -o clothing5.json
# scrapy crawl jewel1 -o jewel1.json
# scrapy crawl jewel2 -o jewel2.json
# scrapy crawl jewel3 -o jewel3.json
# scrapy crawl jewel4 -o jewel4.json
# scrapy crawl jewel5 -o jewel5.json
# scrapy crawl jewel6 -o jewel6.json
# scrapy crawl jewel7 -o jewel7.json
# scrapy crawl jewel8 -o jewel8.json
# scrapy crawl jewel9 -o jewel9.json
# scrapy crawl jewel10 -o jewel10.json
# scrapy crawl jewel11 -o jewel11.json
# scrapy crawl jewel12 -o jewel12.json
# scrapy crawl jewel13 -o jewel13.json
# scrapy crawl jewel14 -o jewel14.json
# scrapy crawl bags1 -o bags1.json
# scrapy crawl bags2 -o bags2.json
# scrapy crawl bags3 -o bags3.json
# scrapy crawl bags4 -o bags4.json
# scrapy crawl bags5 -o bags5.json
# scrapy crawl bags6 -o bags6.json
# scrapy crawl bags7 -o bags7.json
# scrapy crawl bags8 -o bags8.json
# scrapy crawl bags9 -o bags9.json
# scrapy crawl bags10 -o bags10.json
# scrapy crawl bags11 -o bags11.json
# scrapy crawl bags12 -o bags12.json
# scrapy crawl bags13 -o bags13.json
# scrapy crawl bags14 -o bags14.json
# scrapy crawl shoes1 -o shoes1.json
# scrapy crawl shoes2 -o shoes2.json
# scrapy crawl shoes3 -o shoes3.json
# scrapy crawl shoes4 -o shoes4.json
# scrapy crawl shoes5 -o shoes5.json
# scrapy crawl shoes6 -o shoes6.json
# scrapy crawl shoes7 -o shoes7.json
# scrapy crawl shoes8 -o shoes8.json
# scrapy crawl shoes9 -o shoes9.json
# scrapy crawl shoes10 -o shoes10.json
# scrapy crawl shoes11 -o shoes11.json
# scrapy crawl shoes12 -o shoes12.json
# scrapy crawl shoes13 -o shoes13.json
# scrapy crawl cars1 -o cars1.json
# scrapy crawl cars2 -o cars2.json
# scrapy crawl cars3 -o cars3.json
# scrapy crawl cars4 -o cars4.json
# scrapy crawl cars5 -o cars5.json
# scrapy crawl cars6 -o cars6.json
# scrapy crawl cars7 -o cars7.json
# scrapy crawl cars8 -o cars8.json
# scrapy crawl cars9 -o cars9.json
# scrapy crawl cars10 -o cars10.json
# scrapy crawl cars11 -o cars11.json
# scrapy crawl cars12 -o cars12.json
# scrapy crawl cars13 -o cars13.json


