scrapy crawl jewel1 -o jewel1.json
scrapy crawl jewel2 -o jewel2.json
scrapy crawl jewel3 -o jewel3.json
scrapy crawl jewel4 -o jewel4.json
scrapy crawl jewel5 -o jewel5.json
scrapy crawl jewel6 -o jewel6.json
scrapy crawl jewel7 -o jewel7.json
scrapy crawl jewel8 -o jewel8.json
scrapy crawl jewel9 -o jewel9.json
scrapy crawl jewel10 -o jewel10.json
scrapy crawl jewel11 -o jewel11.json
scrapy crawl jewel12 -o jewel12.json
scrapy crawl jewel13 -o jewel13.json
scrapy crawl jewel14 -o jewel14.json