scrapy crawl sports1
scrapy crawl sports2
scrapy crawl sports3
scrapy crawl sports4
scrapy crawl sports5
scrapy crawl sports6
scrapy crawl sports7
scrapy crawl sports8
scrapy crawl sports9
scrapy crawl sports10
scrapy crawl sports11