# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitshopapp', '0004_auto_20160728_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='desc',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='section',
        ),
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
