# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitshopapp', '0005_auto_20160801_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
    ]
