# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitshopapp', '0006_product_sale_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='details',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
