# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-12 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitshopapp', '0013_auto_20160812_0840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='sub_content',
            new_name='subtitle',
        ),
        migrations.RemoveField(
            model_name='news',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='news',
            name='product',
        ),
        migrations.AddField(
            model_name='news',
            name='product',
            field=models.ManyToManyField(blank=True, to='bitshopapp.Product'),
        ),
    ]
