# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-12 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitshopapp', '0014_auto_20160812_0857'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
    ]
