# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-15 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitshopapp', '0015_auto_20160812_0900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='selling_price',
            new_name='brand',
        ),
        migrations.AddField(
            model_name='product',
            name='feature',
            field=models.TextField(null=True),
        ),
    ]
