# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-15 11:40
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitshopapp', '0016_auto_20160815_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100, null=True)),
                ('brand_slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='brand_name')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bitshopapp.Brand'),
        ),
    ]
