# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-15 12:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitshopapp', '0017_auto_20160815_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='brand_slug',
        ),
    ]
