# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-16 08:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitshopapp', '0018_remove_brand_brand_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='downvoted_by',
        ),
        migrations.RemoveField(
            model_name='post',
            name='upvoted_by',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='post',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='downvoted_by',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='upvoted_by',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='upvotes',
        ),
        migrations.RemoveField(
            model_name='subcomment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='subcomment',
            name='downvoted_by',
        ),
        migrations.RemoveField(
            model_name='subcomment',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='subcomment',
            name='upvoted_by',
        ),
        migrations.RemoveField(
            model_name='subcomment',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bitshopapp.Product'),
        ),
        migrations.AddField(
            model_name='subcomment',
            name='subcomment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bitshopapp.Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subcomment',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subcomment',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcomment_requests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subcomment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='subcomment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
