# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-16 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitshopapp', '0021_auto_20160816_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serfoproduct',
            name='super_category',
            field=models.CharField(blank=True, choices=[('M', 'Men'), ('W', 'Women'), ('A', 'Appliances'), ('H', 'Home'), ('E', 'Electronics')], max_length=2, null=True),
        ),
    ]
