# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-16 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitshopapp', '0023_auto_20160816_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='subtitle',
        ),
    ]
