# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-17 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitshopapp', '0024_remove_new_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
