# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-17 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitshopapp', '0026_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='lower_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='upper_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
