# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-18 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitshopapp', '0028_auto_20160818_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bitshopapp.Category'),
        ),
        migrations.AddField(
            model_name='new',
            name='subcategory',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bitshopapp.SubCategory'),
        ),
    ]
