# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-19 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitshopapp', '0030_auto_20160819_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumanswer',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forumanswer',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='forumanswer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bitshopapp.ForumQuestion'),
        ),
        migrations.AlterField(
            model_name='forumquestion',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forumquestion',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='forumquestion',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
