# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-19 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitshopapp', '0031_auto_20160819_0716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='forumanswer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='forumquestion',
            name='user',
        ),
        migrations.DeleteModel(
            name='ForumAnswer',
        ),
        migrations.DeleteModel(
            name='ForumQuestion',
        ),
    ]
