# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitshopapp', '0038_recommendation_rectype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='mac_address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
