# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 09:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bitshopapp', '0039_auto_20161102_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='mac_address',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
