# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitshopapp', '0043_recentlyviewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recentlyviewed',
            name='product',
        ),
        migrations.DeleteModel(
            name='RecentlyViewed',
        ),
    ]
